Floquet Toolkit: src/floquet.c File Reference
floquet.c File Reference
#include "floquet.h"
Functions
int floquet_get_stability_reals_general (int n, void(*A)(double, gsl_matrix *, void *), void *params, double T, gsl_complex *largest_multiplier, double *largest_multiplier_abs)
Function which checks if the function is Floquet Stable or unstable for a general function.
void floquet_get_stability_array_real_single_param_general (int n, void(*A)(double, gsl_matrix *, void *), double T, double start, double end, int nstep, int *stability, gsl_complex *largest_multiplier, double *largest_multiplier_abs)
CPU Parallelized Function which iterates over a range of a parameter and checks if the function is Floquet Stable or unstable for a general function.
void floquet_get_stability_array_real_double_param_general (int n, void(*A)(double, gsl_matrix *, void *), double T, double *start, double *end, int *nstep, int **stability, gsl_complex **largest_multiplier, double **largest_multiplier_abs)
CPU Parallelized Function which iterates over the ranges of 2 parameters and checks if the function is Floquet Stable or unstable for a general function.
Function Documentation
floquet_get_stability_array_real_double_param_general()
void floquet_get_stability_array_real_double_param_general (int n, void(*)(double, gsl_matrix *, void *) A, double T, double * start, double * end, int * nstep, int ** stability, gsl_complex ** largest_multiplier, double ** largest_multiplier_abs)
CPU Parallelized Function which iterates over the ranges of 2 parameters and checks if the function is Floquet Stable or unstable for a general function.
Run floquet_get_stability_reals_general on the ranges of 2 parameters and stores the stability, floquet multiplier corresponding to the largest absolute value, and the absolute value of the largest floquet multiplier. This is a memory naive implementation.
Parameters
n Number of elements of vector that \(A(t) \) operates on
A \(A(t) \) matrix corresponding to the equation \(\dot{x} = Ax \). The void* should be resolved to a double inside the function because a double* with 2 doubles would be passed.
T Period of the evolution function \(A(t) \) s.t. \(A(t + T) = A(t)\ \forall t \in \mathbb{R} \)
start Starting values of the parameters
end Ending values of the parameters
nstep Number of steps to take inclusive of the first and last values keeping the other parameter constant. Should be at least 2. Behaviour not defined otherwise.
largest_multiplier Matrix to store the largest (by abs) computed Floquet multipliers into. No multiplier will be stored if NULL is passed.
largest_multiplier_abs Matrix to store the absolute value of the largest (by abs) computed Floquet multipliers into. No multiplier will be stored if NULL is passed.
Definition at line 110 of file floquet.c.
 {
     gsl_complex** mult_temp;
     double** mult_abs_temp;
     if (largest_multiplier)
     {
         mult_temp = largest_multiplier;
     }
     else
     {
         mult_temp = (gsl_complex**) malloc(nstep[0]*sizeof(gsl_complex*));
         for (int i = 0; i < nstep[0]; ++i)
         {
             mult_temp[i] = (gsl_complex*) malloc(nstep[1]*sizeof(gsl_complex));
         }
     }
     if (largest_multiplier_abs)
     {
         mult_abs_temp = largest_multiplier_abs;
     }
     else
     {
         mult_abs_temp = (double**) malloc(nstep[0]*sizeof(double*));
         for (int i = 0; i < nstep[0]; ++i)
         {
             mult_abs_temp[i] = (double*) malloc(nstep[1]*sizeof(double));
         }
     }
     double step[2] = {(end[0]-start[0])/(nstep[0]-1), (end[1]-start[1])/(nstep[1]-1)};
     #pragma omp parallel for collapse(2) schedule(guided)
     for (int i = 0; i < nstep[0]; ++i)
     {
         for (int j = 0; j < nstep[1]; ++j)
         {
             double param[2] = {start[0] + step[0]*i, start[1] + step[1]*j };
             stability[i][j] = floquet_get_stability_reals_general(n,A,param,T,&mult_temp[i][j],&mult_abs_temp[i][j]);
         }
     }
     if(!largest_multiplier)
     {
         for (int i = 0; i < nstep[0]; ++i)
         {
             free(mult_temp[i]);
         }
         free(mult_temp);
     }
     if(!largest_multiplier_abs)
     {
         for (int i = 0; i < nstep[0]; ++i)
         {
             free(mult_abs_temp[i]);
         }
         free(mult_abs_temp);
     }
 }
References floquet_get_stability_reals_general().
floquet_get_stability_array_real_single_param_general()
void floquet_get_stability_array_real_single_param_general (int n, void(*)(double, gsl_matrix *, void *) A, double T, double start, double end, int nstep, int * stability, gsl_complex * largest_multiplier, double * largest_multiplier_abs)
CPU Parallelized Function which iterates over a range of a parameter and checks if the function is Floquet Stable or unstable for a general function.
Run floquet_get_stability_reals_general on a range of a parameter and stores the stability, floquet multiplier corresponding to the largest absolute value, and the absolute value of the largest floquet multiplier. This is a memory naive implementation.
Parameters
n Number of elements of vector that \(A(t) \) operates on
A \(A(t) \) matrix corresponding to the equation \(\dot{x} = Ax \). The void* should be resolved to a double inside the function because a double* with a single double would be passed.
T Period of the evolution function \(A(t) \) s.t. \(A(t + T) = A(t)\ \forall t \in \mathbb{R} \)
start Starting value of the parameter
end Ending value of the parameter
nstep Number of steps to take inclusive of the first and last values. Should be at least 2. Behaviour not defined otherwise.
largest_multiplier Array to store the largest (by abs) computed Floquet multipliers into. No multiplier will be stored if NULL is passed.
largest_multiplier_abs Array to store the absolute value of the largest (by abs) computed Floquet multipliers into. No multiplier will be stored if NULL is passed.
Definition at line 69 of file floquet.c.
 {
     gsl_complex* mult_temp;
     double* mult_abs_temp;
     if (largest_multiplier)
     {
         mult_temp = largest_multiplier;
     }
     else
     {
         mult_temp = (gsl_complex*) malloc(nstep*sizeof(gsl_complex));
     }
     if (largest_multiplier_abs)
     {
         mult_abs_temp = largest_multiplier_abs;
     }
     else
     {
         mult_abs_temp = (double*) malloc(nstep*sizeof(double));
     }
     double step = (end-start)/(nstep-1);
     #pragma omp parallel for
     for (int i = 0; i < nstep; ++i)
     {
         double param = start + step*i;
         stability[i] = floquet_get_stability_reals_general(n,A,&param,T,mult_temp+i,mult_abs_temp+i);
     }
     if(!largest_multiplier)
     {
         free(mult_temp);
     }
     if(!largest_multiplier_abs)
     {
         free(mult_abs_temp);
     }
 }
References floquet_get_stability_reals_general().
floquet_get_stability_reals_general()
int floquet_get_stability_reals_general (int n, void(*)(double, gsl_matrix *, void *) A, void * params, double T, gsl_complex * largest_multiplier, double * largest_multiplier_abs)
Function which checks if the function is Floquet Stable or unstable for a general function.
Naive implementation with the elements of the \(X(T) \) matrix calculated to precision ERR_TOL
Parameters
n Number of elements of vector that \(A(t) \) operates on
A \(A(t) \) matrix corresponding to the equation \(\dot{x} = Ax \)
params Parameters to be passed to \(A(t) \)
T Period of the evolution function \(A(t) \) s.t. \(A(t + T) = A(t)\ \forall t \in \mathbb{R} \)
largest_multiplier Pointer to store the largest (by abs) computed Floquet multiplier into. No multiplier will be stored if NULL is passed.
largest_multiplier_abs Pointer to store the absolute value of the largest (by abs) computed Floquet multiplier into. No multiplier will be stored if NULL is passed.
Returns
1 if Stable, -1 if unstable, 0 if periodic or indeterminate to accuracy ERR_EIGEN_TOL. In rare cases, 2 would be returned if none of the computed floquet multipliers lead to instability, but not all of multipliers could be computed.
Definition at line 4 of file floquet.c.
 {
     gsl_matrix* X = gsl_matrix_alloc(n,n);
     gsl_matrix_set_identity(X);
     gsl_matrix* B = gsl_matrix_alloc(n,n);
     bulsto_final_matrix_floquet_type_real(X, 0., T, ERR_TOL, A, B, params);
     gsl_vector_complex* eigenvals = gsl_vector_complex_alloc(n);
     gsl_eigen_nonsymm_workspace* w = gsl_eigen_nonsymm_alloc(n);
     int n_eigenvals_evaluated = n;
     int err_code = gsl_eigen_nonsymm(B,eigenvals,w);
     if(err_code)
     {
         n_eigenvals_evaluated = w->n_evals;
     }
     double mult_max_abs = -HUGE_VAL;
     gsl_complex mult_max;
     double ev_test;
     for (int i = 0; i < n_eigenvals_evaluated; ++i)
     {
         ev_test = gsl_complex_logabs(gsl_vector_complex_get(eigenvals,i));
         if (mult_max_abs < ev_test)
         {
             mult_max_abs = ev_test;
             mult_max = gsl_vector_complex_get(eigenvals,i);
         }
     }
     if (largest_multiplier != NULL)
     {
         *largest_multiplier = mult_max;
     }
     if (largest_multiplier_abs != NULL)
     {
         *largest_multiplier_abs = gsl_complex_abs(mult_max);
     }
     gsl_eigen_nonsymm_free(w);
     gsl_vector_complex_free(eigenvals);
     gsl_matrix_free(B);
     gsl_matrix_free(X);
     if (mult_max_abs > ERR_EIGEN_TOL)
     {
         return 1;
     }
     else if (mult_max_abs < (-ERR_EIGEN_TOL))
     {
         if (n_eigenvals_evaluated < n)
         {
             return 2;
         }
         return -1;
     }
     else
     {
         return 0;
     }
 }
References bulsto_final_matrix_floquet_type_real(), ERR_EIGEN_TOL, and ERR_TOL.
Referenced by floquet_get_stability_array_real_double_param_general(), and floquet_get_stability_array_real_single_param_general().